# fly.toml app configuration file generated for torrent-fish on 2023-04-29T22:21:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "torrent-fish"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "bos"
processes = []

[build]

[env]

[[services]]
  internal_port = 6881
  processes = []
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200
    type = "connections"

  [[services.ports]]
    port = 6881

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
