# fly.toml app configuration file generated for torrent-fish on 2023-04-29T22:45:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "torrent-fish"
primary_region = "bos"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PRIMARY_REGION = "bos"

[[services]]
  protocol = "tcp"
  internal_port = 6881

  [[services.ports]]
    port = 6881
  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
